/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Operaciones;


import Operaciones.*;
import Paneles.Inventario.*;
import Concesionario.Main;
import Info.Credenciales;
import Info.Inventario;
import Operaciones.Busqueda;
import Operaciones.Crud_txt;
import static Paneles.Login.Login.panel;
import Tipografias.Fuentes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stephen
 */
public class Gestion_inv extends javax.swing.JPanel {

    /**
     * Creates new form Gerente_inv
     */
    static DefaultTableModel modelo;

    static List<Inventario> ListaInventario = new ArrayList<Inventario>();

    public Gestion_inv() {
        initComponents();
        inicializar();

    }

    public static void inicializar() {
        ListaInventario = new ArrayList<Inventario>();
        Crud_txt lector = new Crud_txt();
        ListaInventario = lector.leer_Inventario_U();
        modelo = (DefaultTableModel) TablaInv.getModel();
        modelo.setRowCount(0);
        BarraBusqueda.setText("");
        //System.out.println(ListaInventario.get(0).getMarca() +" "+ListaInventario.get(0).getModelo()+" "+ListaInventario.get(0).getAbs()+" "+ListaInventario.get(0).getAireA()+" "+ListaInventario.get(0).getCilindraje()+" "+ListaInventario.get(0).getCombustible()+" "+ListaInventario.get(0).getDireccion()+" "+ListaInventario.get(0).getEspEle()+" "+ListaInventario.get(0).getF_fabricacion()+" "+ListaInventario.get(0).getImagen()+" "+ListaInventario.get(0).getKilometraje()+" "+ListaInventario.get(0).getPantTac()+" "+ListaInventario.get(0).getPlaca()+" "+ListaInventario.get(0).getPrecio()+" "+ListaInventario.get(0).getSensor()+" "+ListaInventario.get(0).getTransmision()+" "+ListaInventario.get(0).getVelmax()+" "+ListaInventario.get(0).getVidriosEl());
        int contador=0;
        for (Inventario item : ListaInventario) {
            Object[] rowData = {
                             
                item.getMarca(),
                item.getModelo(),
                item.getF_fabricacion(),
                item.getCilindraje(),
                item.getPlaca(),
                item.getPrecio(),
                item.getKilometraje(),
                contador
                
            };
            modelo.addRow(rowData);
            contador++;
        }

    }
public void busqueda(){
        Busqueda.indices.clear();
        modelo.setRowCount(0);
        
        List<Inventario> resultado =Busqueda.filtrar(ListaInventario, Filtro_jp.getSelectedItem().toString(), BarraBusqueda.getText()) ;        
        System.out.println(resultado.size());

        //System.out.println(ListaInventario.get(0).getMarca() +" "+ListaInventario.get(0).getModelo()+" "+ListaInventario.get(0).getAbs()+" "+ListaInventario.get(0).getAireA()+" "+ListaInventario.get(0).getCilindraje()+" "+ListaInventario.get(0).getCombustible()+" "+ListaInventario.get(0).getDireccion()+" "+ListaInventario.get(0).getEspEle()+" "+ListaInventario.get(0).getF_fabricacion()+" "+ListaInventario.get(0).getImagen()+" "+ListaInventario.get(0).getKilometraje()+" "+ListaInventario.get(0).getPantTac()+" "+ListaInventario.get(0).getPlaca()+" "+ListaInventario.get(0).getPrecio()+" "+ListaInventario.get(0).getSensor()+" "+ListaInventario.get(0).getTransmision()+" "+ListaInventario.get(0).getVelmax()+" "+ListaInventario.get(0).getVidriosEl());
        for (Inventario item : resultado) {
            String[] rowData = {
                item.getMarca(),
                item.getModelo(),
                item.getF_fabricacion(),
                item.getCilindraje(),
                item.getPlaca(),
                item.getPrecio(),
                item.getKilometraje()
            };
            modelo.addRow(rowData);
        }
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
            modelo.setValueAt(Busqueda.indices.get(i), i, 7); // Columna 7 (índice 6)
        }
        

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ficha_jp = new javax.swing.JButton();
        eliminar_jp = new javax.swing.JButton();
        agregar_jp = new javax.swing.JButton();
        editar_jp = new javax.swing.JButton();
        BarraBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInv = new javax.swing.JTable();
        Filtro_jp = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ficha_jp.setBorder(null);
        ficha_jp.setContentAreaFilled(false);
        ficha_jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha_jpActionPerformed(evt);
            }
        });
        add(ficha_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 180, 50));

        eliminar_jp.setBorder(null);
        eliminar_jp.setContentAreaFilled(false);
        eliminar_jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_jpActionPerformed(evt);
            }
        });
        add(eliminar_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 660, 180, 50));

        agregar_jp.setBorder(null);
        agregar_jp.setContentAreaFilled(false);
        agregar_jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jpActionPerformed(evt);
            }
        });
        add(agregar_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 190, 50));

        editar_jp.setBorder(null);
        editar_jp.setContentAreaFilled(false);
        editar_jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_jpActionPerformed(evt);
            }
        });
        add(editar_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 660, 190, 50));

        BarraBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BarraBusqueda.setBorder(null);
        BarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraBusquedaActionPerformed(evt);
            }
        });
        BarraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarraBusquedaKeyReleased(evt);
            }
        });
        add(BarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 20));

        TablaInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "F.Fabricacion", "Cilindraje", "Placa", "Precio", "Kilometraje", "#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaInv);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 880, 430));

        Filtro_jp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca", "Modelo", "F_Fabricacion", "Cilindraje", "Placa", "Precio", "Kilometraje" }));
        Filtro_jp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Filtro_jpItemStateChanged(evt);
            }
        });
        add(Filtro_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 125, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Por");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 125, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Gerente_inv.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBusquedaActionPerformed

    private void agregar_jpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jpActionPerformed

        Main.ShowPanel("Agregar_inv");

    }//GEN-LAST:event_agregar_jpActionPerformed

    private void ficha_jpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha_jpActionPerformed
        int fila = TablaInv.getSelectedRow();
        
   if(fila==-1){
                   JOptionPane.showMessageDialog(null, "Seleccione una fila", "Error", JOptionPane.INFORMATION_MESSAGE);
                   
   }else{        
       int elemento=(int)(TablaInv.getValueAt(fila, 7));
        Main.ShowPanel("VerFicha_inv");
        Main.verficha_inv.Inicializar(ListaInventario.get(elemento).getMarca(), ListaInventario.get(elemento).getModelo(), ListaInventario.get(elemento).getF_fabricacion(), ListaInventario.get(elemento).getPlaca(), ListaInventario.get(elemento).getTransmision(), ListaInventario.get(elemento).getCombustible(), ListaInventario.get(elemento).getCilindraje(), ListaInventario.get(elemento).getAbs(), ListaInventario.get(elemento).getSensor(), ListaInventario.get(elemento).getAireA(), ListaInventario.get(elemento).getVidriosEl(), ListaInventario.get(elemento).getPantTac(), ListaInventario.get(elemento).getDireccion(), ListaInventario.get(elemento).getEspEle(), ListaInventario.get(elemento).getVelmax(), ListaInventario.get(elemento).getKilometraje(),ListaInventario.get(elemento).getImagen(), ListaInventario.get(elemento).getPrecio());
   
   }
        
        
    }//GEN-LAST:event_ficha_jpActionPerformed

    private void editar_jpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_jpActionPerformed
        int fila = TablaInv.getSelectedRow();
        
   if(fila==-1){
                   JOptionPane.showMessageDialog(null, "Seleccione una fila", "Error", JOptionPane.INFORMATION_MESSAGE);
   
   }else{
int elemento=(int) TablaInv.getValueAt(fila, 7);
               Main.ShowPanel("Editar_inv");
        Main.editar_inv.Inicializar(elemento,ListaInventario,ListaInventario.get(elemento).getMarca(), ListaInventario.get(elemento).getModelo(), ListaInventario.get(elemento).getF_fabricacion(), ListaInventario.get(elemento).getPlaca(), ListaInventario.get(elemento).getTransmision(), ListaInventario.get(elemento).getCombustible(), ListaInventario.get(elemento).getCilindraje(), ListaInventario.get(elemento).getAbs(), ListaInventario.get(elemento).getSensor(), ListaInventario.get(elemento).getAireA(), ListaInventario.get(elemento).getVidriosEl(), ListaInventario.get(elemento).getPantTac(), ListaInventario.get(elemento).getDireccion(), ListaInventario.get(elemento).getEspEle(), ListaInventario.get(elemento).getVelmax(), ListaInventario.get(elemento).getKilometraje(),ListaInventario.get(elemento).getImagen(), ListaInventario.get(elemento).getPrecio());
             
   }
    }//GEN-LAST:event_editar_jpActionPerformed

    private void eliminar_jpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_jpActionPerformed
                int fila = TablaInv.getSelectedRow();
   if(fila==-1){
                   JOptionPane.showMessageDialog(null, "Seleccione una fila", "Error", JOptionPane.INFORMATION_MESSAGE);
   
   }else{   
int elemento=(int) TablaInv.getValueAt(fila, 7);
Main.ShowPanel("Eliminar_inv");
        Main.eliminar_inv.Inicializar(elemento,ListaInventario,ListaInventario.get(elemento).getMarca(), ListaInventario.get(elemento).getModelo(), ListaInventario.get(elemento).getF_fabricacion(), ListaInventario.get(elemento).getPlaca(), ListaInventario.get(elemento).getTransmision(), ListaInventario.get(elemento).getCombustible(), ListaInventario.get(elemento).getCilindraje(), ListaInventario.get(elemento).getAbs(), ListaInventario.get(elemento).getSensor(), ListaInventario.get(elemento).getAireA(), ListaInventario.get(elemento).getVidriosEl(), ListaInventario.get(elemento).getPantTac(), ListaInventario.get(elemento).getDireccion(), ListaInventario.get(elemento).getEspEle(), ListaInventario.get(elemento).getVelmax(), ListaInventario.get(elemento).getKilometraje(),ListaInventario.get(elemento).getImagen(), ListaInventario.get(elemento).getPrecio());
      
   }
    }//GEN-LAST:event_eliminar_jpActionPerformed

    private void BarraBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraBusquedaKeyReleased
busqueda();
        
    }//GEN-LAST:event_BarraBusquedaKeyReleased

    private void Filtro_jpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Filtro_jpItemStateChanged
      busqueda();
    }//GEN-LAST:event_Filtro_jpItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField BarraBusqueda;
    private javax.swing.JComboBox<String> Filtro_jp;
    private static javax.swing.JTable TablaInv;
    private javax.swing.JButton agregar_jp;
    private javax.swing.JButton editar_jp;
    private javax.swing.JButton eliminar_jp;
    private javax.swing.JButton ficha_jp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
