/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles.Ventas;

import Concesionario.Main;
import Contrato.GenerarContrato;
import Info.Inventario;
import Operaciones.Crud_txt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen
 */
public class Form_ven extends javax.swing.JPanel {

    public static Inventario auto;
    
    public Form_ven() {
        initComponents();
    }

    public void Vaciar() {
                
        Apellidos_T.setText("");
        Cedula_T.setText("");
        Celular_T.setText("");
        Domicilio_T.setText("");
        Email_T.setText("");
        Nombres_T.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cedula_T = new javax.swing.JTextField();
        Email_T = new javax.swing.JTextField();
        Celular_T = new javax.swing.JTextField();
        Domicilio_T = new javax.swing.JTextField();
        Apellidos_T = new javax.swing.JTextField();
        Nombres_T = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 637, 160, 41));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 53, 160, 41));

        Cedula_T.setBorder(null);
        add(Cedula_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 524, 340, 50));

        Email_T.setBorder(null);
        add(Email_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 417, 340, 50));

        Celular_T.setBorder(null);
        add(Celular_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 310, 340, 50));

        Domicilio_T.setBorder(null);
        add(Domicilio_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 524, 340, 50));

        Apellidos_T.setBorder(null);
        add(Apellidos_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 416, 340, 50));

        Nombres_T.setBorder(null);
        add(Nombres_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 308, 340, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Form_venta.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Main.ShowPanel("VerFicha_ven");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GenerarContrato generarcontrato = new GenerarContrato("Representante de la empresa", "Bogotá D.C.", "C.C del representante", (Apellidos_T.getText() + " " + Nombres_T.getText()), Domicilio_T.getText(), Cedula_T.getText(), auto.getMarca(), auto.getModelo(), auto.getPlaca(), auto.getCilindraje(), auto.getPrecio());
        JOptionPane.showMessageDialog(null, "¡Contrato Generado!", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        
        
        Crud_txt lector= new Crud_txt();
        
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setStatus("Si");  
        
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setNombreCom(Nombres_T.getText());
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setNumeroCom(Celular_T.getText());  
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setApellidosCom(Apellidos_T.getText());  
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setEmailCom(Email_T.getText());  
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setCiudadCom(Domicilio_T.getText());  
        VerFicha_ven.ListaInventario.get(VerFicha_ven.Auto_indice).setCedulaCom(Cedula_T.getText());  
        
        lector.Editar_Inventario_U(VerFicha_ven.ListaInventario);

        Vaciar();
        Main.ShowPanel("Gerente_Ventas");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos_T;
    private javax.swing.JTextField Cedula_T;
    private javax.swing.JTextField Celular_T;
    private javax.swing.JTextField Domicilio_T;
    private javax.swing.JTextField Email_T;
    private javax.swing.JTextField Nombres_T;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
