/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles.Inventario;

import Paneles.Ventas.*;
import Concesionario.Main;
import Contrato.GenerarContrato;
import Info.Inventario;
import Operaciones.Crud_txt;
import Operaciones.Gestion_inv;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen
 */
public class DatosCom_inv extends javax.swing.JPanel {

    public static Inventario auto;

    public DatosCom_inv() {
        initComponents();
    }

    public void Vaciar() {

        Apellidos_T.setText("");
        Cedula_T.setText("");
        Celular_T.setText("");
        Domicilio_T.setText("");
        Email_T.setText("");
        Nombres_T.setText("");

    }

    public static void Inicializar() {

        Apellidos_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getApellidosCom()
        );
        Cedula_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getCedulaCom()
        );
        Celular_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getNumeroCom()
        );
        Domicilio_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getCiudadCom()
        );
        Email_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getEmailCom()
        );
        Nombres_T.setText(Gestion_inv.ListaInventario.get(Gestion_inv.indice).getNombreCom()
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Cedula_T = new javax.swing.JTextField();
        Email_T = new javax.swing.JTextField();
        Celular_T = new javax.swing.JTextField();
        Domicilio_T = new javax.swing.JTextField();
        Apellidos_T = new javax.swing.JTextField();
        Nombres_T = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 53, 160, 41));

        Cedula_T.setEditable(false);
        Cedula_T.setBackground(new java.awt.Color(255, 255, 255));
        Cedula_T.setBorder(null);
        add(Cedula_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 524, 340, 50));

        Email_T.setEditable(false);
        Email_T.setBackground(new java.awt.Color(255, 255, 255));
        Email_T.setBorder(null);
        add(Email_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 417, 340, 50));

        Celular_T.setEditable(false);
        Celular_T.setBackground(new java.awt.Color(255, 255, 255));
        Celular_T.setBorder(null);
        add(Celular_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 310, 340, 50));

        Domicilio_T.setEditable(false);
        Domicilio_T.setBackground(new java.awt.Color(255, 255, 255));
        Domicilio_T.setBorder(null);
        add(Domicilio_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 524, 340, 50));

        Apellidos_T.setEditable(false);
        Apellidos_T.setBackground(new java.awt.Color(255, 255, 255));
        Apellidos_T.setBorder(null);
        add(Apellidos_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 416, 340, 50));

        Nombres_T.setEditable(false);
        Nombres_T.setBackground(new java.awt.Color(255, 255, 255));
        Nombres_T.setBorder(null);
        add(Nombres_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 308, 340, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/DatosCom.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Main.ShowPanel("VerFicha_inv");
        Vaciar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField Apellidos_T;
    private static javax.swing.JTextField Cedula_T;
    private static javax.swing.JTextField Celular_T;
    private static javax.swing.JTextField Domicilio_T;
    private static javax.swing.JTextField Email_T;
    private static javax.swing.JTextField Nombres_T;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
