/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MenuPanels;

import Concesionario.Main;
import javax.swing.ImageIcon;

/**
 *
 * @author Stephen
 */
public class Menu_Gerente extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Gerente
     */
    public Menu_Gerente() {
        initComponents();
    }
    static ImageIcon icono;

    public static void setMenu(int var) {

        switch (var) {
            case 0:
                icono = new ImageIcon("src/MenuPanels/MenuImg/MenuVentas.png");
                Menu_jp.setIcon(icono);
                break;
            case 1:
                icono = new ImageIcon("src/MenuPanels/MenuImg/MenuInventario.png");
                Menu_jp.setIcon(icono);
                break;
            case 2:
                icono = new ImageIcon("src/MenuPanels/MenuImg/MenuAgendar.png");
                Menu_jp.setIcon(icono);
                break;
            case 3:
                icono = new ImageIcon("src/MenuPanels/MenuImg/MenuPerfil.png");
                Menu_jp.setIcon(icono);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Menu_jp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 50, 50));

        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 465, 50, 55));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 40, 50));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 49, 45));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 42, 50));
        add(Menu_jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 93, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        icono = new ImageIcon("src/MenuPanels/MenuImg/MenuVentas.png");
        Menu_jp.setIcon(icono);
        Main.ShowPanel("Gerente_Ventas");
        jButton2.setVisible(false);
        jButton4.setVisible(true);
        jButton3.setVisible(true);
        jButton1.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        icono = new ImageIcon("src/MenuPanels/MenuImg/MenuInventario.png");
        Menu_jp.setIcon(icono);
        Main.ShowPanel("Gerente_inv");

        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(true);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        icono = new ImageIcon("src/MenuPanels/MenuImg/MenuAgendar.png");
        Menu_jp.setIcon(icono);
        Main.ShowPanel("Gestion_man");
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(false);
        jButton1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        icono = new ImageIcon("src/MenuPanels/MenuImg/MenuPerfil.png");
        Menu_jp.setIcon(icono);
        jButton2.setVisible(true);
        jButton4.setVisible(false);
        jButton3.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Main.ShowPanel("login");
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Menu_jp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
